//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.24 at 08:58:12 PM CEST 
//


package centralbank.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the centralbank.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: centralbank.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Faktura }
     * 
     */
    public Faktura createFaktura() {
        return new Faktura();
    }

    /**
     * Create an instance of {@link NalogZaPrenos }
     * 
     */
    public NalogZaPrenos createNalogZaPrenos() {
        return new NalogZaPrenos();
    }

    /**
     * Create an instance of {@link Faktura.ZaglavljeFakture }
     * 
     */
    public Faktura.ZaglavljeFakture createFakturaZaglavljeFakture() {
        return new Faktura.ZaglavljeFakture();
    }

    /**
     * Create an instance of {@link Faktura.StavkaFakture }
     * 
     */
    public Faktura.StavkaFakture createFakturaStavkaFakture() {
        return new Faktura.StavkaFakture();
    }

    /**
     * Create an instance of {@link TPreduzece }
     * 
     */
    public TPreduzece createTPreduzece() {
        return new TPreduzece();
    }

    /**
     * Create an instance of {@link TRacun }
     * 
     */
    public TRacun createTRacun() {
        return new TRacun();
    }

    /**
     * Create an instance of {@link NalogZaPrenos.PodaciOUplati }
     * 
     */
    public NalogZaPrenos.PodaciOUplati createNalogZaPrenosPodaciOUplati() {
        return new NalogZaPrenos.PodaciOUplati();
    }

}
