//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.28 at 02:21:29 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
		 xmlns = { 
			        @XmlNs(prefix="presek",namespaceURI = "http://www.ftn.uns.ac.rs/presek"),
			        @XmlNs(prefix="nalog",namespaceURI = "http://www.ftn.uns.ac.rs/nalogZaPrenos"),
			        @XmlNs(prefix="zahtev", namespaceURI ="http://www.ftn.uns.ac.rs/ZahtevZaIzvod")
			    }
		)
package company.bean;

import javax.xml.bind.annotation.XmlNs;
